name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - tset2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        # No 'Build Artifacts' step needed, as the build/ folder is already in the repo.

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Ensure this is your correct AWS region.

      - name: Verify AWS Credentials (Optional Debugging)
        run: aws sts get-caller-identity

      - name: Upload Files to S3
        run: aws s3 cp build/ s3://aparna-github-actions-test-bucket/deployments/ --recursive
        # IMPORTANT:  Double-check that 'build/' is the correct path *within your repository*
        #             to the files you want to upload.

      
                
