name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Artifacts (Replace with your actual build process)
        run: |
          mkdir -p build
          echo "Hello, S3!" > build/index.html
          #  Add your actual build commands here.  This is just an example.
          #  For example, if you have a Node.js project:
          #  npm install
          #  npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Make sure this is the correct region

      - name: Verify AWS Credentials (Optional, for debugging)
        run: aws sts get-caller-identity

      - name: Upload Files to S3
        run: aws s3 cp build/ s3://aparna-github-actions-test-bucket/deployments/ --recursive

      - name: Invalidate CloudFront Cache
        run: |
          INVALIDATION_BATCH=$(jq -n \
            --arg paths '/deployments/index.html' \
            --arg callerRef "$(date +%s)" \
            '{Paths: {Quantity: 1, Items: [$paths]}, CallerReference: $callerRef}' \
          )
          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" \
            --invalidation-batch "$INVALIDATION_BATCH"
        continue-on-error: true

      - name: Check CloudFront Invalidation and Notify on Failure
        if: failure()  # Runs only if the *previous* step (invalidation) failed
        run: |
          echo "CloudFront invalidation failed!"
          echo "::warning:: CloudFront invalidation failed.  Check workflow logs."
          #  Add a more robust notification method here (e.g., Slack, email).
          #  This is just a basic example.  See previous responses for notification examples.
